### ISSUE TITLE
Indicator crashes when trying to play sounds in ubuntu 16.04

### ISSUE THREAD

**Issue by wisedevman** [atareao/pomodoro-indicator#9]
As the title says, the app crashes when it calls pyglet media library.

The reason is that in ubuntu 16.04 avlib is missing. That is required by pyglet to play .ogg files. It appears not longer mantained, so there's not package available.

So i'm asking if it'd be the case to change the sound library pomodoro's using.
Waiting to hear from you about it.

**Comment by atareao** [comment]
It's time to change the sound library... 
Thank you very much.

**Comment by ferossan** [comment]
From Terminal:
$ pomodoro-indicator
/usr/bin/pomodoro-indicator:29: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "/usr/bin/pomodoro-indicator", line 37, in <module>
    from pomodoro_indicator import main
  File "/usr/share/pomodoro-indicator/pomodoro_indicator.py", line 45, in <module>
    from player import Player
  File "/usr/bin/player.py", line 14, in <module>
    from PIL import Image, ImageTk
ImportError: cannot import name 'ImageTk'

**Comment by wisedevman** [comment]
sudo apt install python3-tk

**Comment by wisedevman** [comment]
sudo apt-get purge python3-pil
sudo apt-get install python3-pil python3-pil.imagetk

**Comment by ferossan** [comment]
Didn't work. python3-tk was already installed. Re-installed python3-pil and python3-pil.imagetk and here is what happens running pomodoro-indocator from the terminal:
$ pomodoro-indicator
/usr/bin/pomodoro-indicator:29: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "/usr/bin/pomodoro-indicator", line 37, in <module>
    from pomodoro_indicator import main
  File "/usr/share/pomodoro-indicator/pomodoro_indicator.py", line 45, in <module>
    from player import Player
ImportError: cannot import name 'Player'

**Comment by atareao** [comment]
I'm so sorry... There is a big bug. I am away and I can't fix now. I'll fix it wednesday...

**Comment by atareao** [comment]
Fixed.... :+1:
